name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install coverage tool
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr

    - name: build
      run: g++ -Wall -Wextra -fprofile-arcs -ftest-coverage -o send *.c*
      
    - name: run help
      run: ./send
      
    - name: run test
      run: ./send -t
      
    - name: run application
      run: ./send -r

    - name: collect coverage
      run: gcovr --gcov-exclude=".*test.*" -r . --html --html-details -o coverage.html --print-summary

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./*.html
        retention-days: 21


    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies For Receiver part in Python
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install coverage
        pip install pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
    - name: Run and collect coverage
      run: |
        coverage run -m pytest
        coverage html
        coverage report
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./htmlcov
        retention-days: 21

    - name: run the pipeline from sender to Receiver
      run: send.exe -r > Receiver\data.csv
      run: python Receiver\ReceiverMain.py

    

